### ISSUE TITLE
[feature] Support for Terraform Cloud - Enterprise 

### ISSUE THREAD

**Issue by arnaudlh** [Azure/caf-terraform-landingzones#96]
## Already supported scenario 

- [X]  1. Create the TFE/TFC environment (organization, variables, workspaces)

## Future scenarios:
- [ ]  1. Use TFC as remote backend (local execution, backend stored in TFC)
- [ ]  2. Use TFC with Terraform Cloud Agents (https://www.terraform.io/docs/cloud/workspaces/agent.html)
- [ ]  3. Deploy Terraform Enterprise Server and remote agents
- [ ]  4. Use TFE in online mode (execution in TFE with remote agents)

**Comment by hyperfocus1337** [comment]
Is it going to be possible to use terraform cloud as an alternative for Azure Storage Accounts and Keyvault in the level 0 landing zone?
